stages:
  - test
  - sbom
  - report

default:
  tags:
    - flarenetwork
  artifacts:
    expire_in: 3 days

include:
  - component: gitlab.com/flarenetwork/ci-components-private/lgtm@2
  - component: gitlab.com/flarenetwork/ci-components-private/dependency-track@2
  - component: gitlab.com/flarenetwork/ci-components-private/lint-dockerfile@2
  - component: gitlab.com/flarenetwork/ci-components-private/lint-shell@2
  - component: gitlab.com/flarenetwork/ci-components-private/test-go@2
    inputs:
      go_version: "1.26.4"
  - component: gitlab.com/flarenetwork/ci-components-private/lint-go@2
    inputs:
      go_version: "1.26.4"
      golangci_version: "v2.11.3"
      golangci_config_file: ".golangci.yml"
  - template: Jobs/Secret-Detection.latest.gitlab-ci.yml
  - component: gitlab.com/flarenetwork/ci-components-private/ai-code-review@2
    inputs:
      job_name_suffix: "-mr"
      model_backend: "gemini"
      rules_condition: $CI_MERGE_REQUEST_IID != null && $GITLAB_USER_NAME != "SealBot" && $CI_MERGE_REQUEST_EVENT_TYPE != "merge_train"
      rules_when: always
  - component: gitlab.com/flarenetwork/ci-components-private/ai-code-review@2
    inputs:
      job_name_suffix: "-repo"
      model_backend: "gemini"
      tags: ["flarenetwork-lg-cpu"]
      rules_condition: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      rules_when: manual
      repo_review_mode: true
