version: "2"
run:
  go: "1.25.1"
  modules-download-mode: readonly
linters:
  default: standard
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - decorder
    - errchkjson
    - errname
    - exhaustive
    - exptostd
    - forcetypeassert
    - misspell
    - nolintlint
    - unconvert
    - whitespace

    - modernize
    - thelper
    - usestdlibvars
    - usetesting
    - unparam
    - predeclared
    - prealloc

  settings:
    exhaustive:
      default-signifies-exhaustive: true
    nolintlint:
      require-specific: true
exclusions:
  generated: lax
  paths:
    - third_party$
    - builtin$
    - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-same-issues: 3
