version: "2"
run:
  go: 1.23.8
  modules-download-mode: readonly
linters:
  default: standard
  enable:
    - whitespace
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
